export default [
  {
    title: "Salat",
    note: "Zu allen Salaten gibt es veganes Roggenbrot.",
    products: [
      {
        title: "Kleiner gemischter Salat",
        vegan: true,
        description: "(Weisskraut, Möhren, Gurkenscheiben, Oliven)",
        price: 4.8,
      },
      {
        title: "Griechischer Salat",
        vegan: false,
        description:
          "(Eichblattsalat, Gurken, Tomaten, Krautsalat, Zwiebeln, frischer Schafskäse, Oliven und Pepperoni)",
        price: "7.50",
        variants: [
          { variant: "Groß (+1,50€)" },
          { variant: "mit Knoblauch (+0,50€)" },
          { variant: "ohne Schafskäse auch gerne Vegan" },
        ],
      },
    ],
  },
  {
    title: "Kleinigkeiten",
    note: "",
    products: [
      {
        title: "Oliven",
        vegan: true,
        description: "(grün, geschwärzt oder gemischt)",
        price: "2.50",
        variants: [],
      },
      {
        title: "Pepperoni",
        vegan: true,
        description: "(mild, scharf oder gemischt)",
        price: "2.50",
        variants: [],
      },
      {
        title: "Pizzabrot",
        vegan: true,
        description: "",
        price: "3.50",
        variants: [],
      },
      {
        title: "Pizzabrot mit Knoblauch",
        vegan: true,
        description: "",
        price: 4,
        variants: [],
      },
      {
        title: "Tsatziki mit Pizzabrot",
        vegan: false,
        description: "",
        price: 6,
        variants: [],
      },
    ],
  },
  {
    title: "Pizza",
    note: "Alle Pizzen gibt es auch mit hausgemachtem Vegankäse.",
    products: [
      {
        title: "Pizza Vegetarischer Bolognese",
        vegan: false,
        description: "(mit Grünkern und Käse)",
        price: "7.50",
        variants: [],
      },
      {
        title: "Pizza Bolognese",
        vegan: false,
        description: "(mit Hackfleischsoße und Käse)",
        price: "7.50",
        variants: [],
      },
      {
        title: "Pizza Napoli",
        vegan: false,
        description: "(mit Tomatensoße und Käse)",
        price: 6,
        variants: [],
      },
    ],
  },
  {
    title: "Pasta",
    note: "mit Käse oder hausgemachtem Vegankäse überbacken (+0,50€)",
    products: [
      {
        title: "Tortellini Tricolore",
        vegan: false,
        description: "(vegetarische Nudeltaschen mit Käse-Füllung)",
        price: 7,
        variants: [
          {
            variant:
              "mit Käse oder hausgemachtem Vegankäse überbacken (+0,50€)",
          },
          { variant: "mit Sahnesoße" },
          { variant: "mit Bolognesesoße" },
          { variant: "Tomaten-Knoblauch-Soße" },
          { variant: "Gorgonzola-Sahne-Soße" },
          { variant: "Vegetarische Bolognese" },
        ],
      },
      {
        title: "Tagliatelle Verdi",
        vegan: true,
        description: "(grüne Bandnudeln)",
        price: 7,
        variants: [
          {
            variant:
              "mit Käse oder hausgemachtem Vegankäse überbacken (+0,50€)",
          },
          { variant: "Sahnesoße" },
          { variant: "Bolognesesoße" },
          { variant: "Tomaten-Knoblauch-Soße" },
          { variant: "Gorgonzola-Sahne-Soße" },
          { variant: "Vegetarische Bolognese" },
        ],
      },
      {
        title: "Fusilli",
        vegan: true,
        description: "(kleine Zopfnudeln)",
        price: 7,
        variants: [
          {
            variant:
              "mit Käse oder hausgemachtem Vegankäse überbacken (+0,50€)",
          },
          { variant: "Sahnesoße" },
          { variant: "Bolognesesoße" },
          { variant: "Tomaten-Knoblauch-Soße" },
          { variant: "Gorgonzola-Sahne-Soße" },
          { variant: "Vegetarische Bolognese" },
        ],
      },
      {
        title: "Spaghetti",
        vegan: false,
        description: "",
        price: 7,
        variants: [
          {
            variant:
              "mit Käse oder hausgemachtem Vegankäse überbacken (+0,50€)",
          },
          { variant: "Sahnesoße" },
          { variant: "Bolognesesoße" },
          { variant: "Tomaten-Knoblauch-Soße" },
          { variant: "Gorgonzola-Sahne-Soße" },
          { variant: "Vegetarische Bolognese" },
        ],
      },
    ],
  },
  {
    title: "Mit Fleisch",
    note: "mit Salat und Tsatziki, dazu Reis oder Ofenkartoffeln",
    products: [
      {
        title: "Feurig scharfes Chili Con Carne",
        vegan: false,
        description:
          "(mit roten Bohnen, Hackfleisch, Paprika, Mais, Zwiebeln und Knoblauch)",
        price: "7.50",
        variants: [],
      },
      {
        title: "Kjeftedes",
        vegan: false,
        description:
          "(griechische Hackfleischbällchen mit Hirtenkäse und Pepperoni)",
        price: "11.50",
        variants: [
          { variant: "mit Salat und Tsatziki, dazu Reis oder Ofenkartoffeln" },
        ],
      },
    ],
  },
  {
    title: "Vegetarisch",
    note: "",
    products: [
      {
        title: "Tsatziki und Ofenkartoffeln",
        vegan: false,
        description: "mit Salat garniert",
        price: "9.50",
        variants: [],
      },
      {
        title: "Käsespätzle",
        vegan: false,
        description: "(mit kleinem Salat und Apfelmus)",
        price: "9.50",
        variants: [],
      },
      {
        title: "Gebackener Schafskäse",
        vegan: false,
        description: "mit Knoblauch, Salatgarnitur und Brot",
        price: "6.50",
        variants: [],
      },
      {
        title: "Süßkartoffel-Kokos–Curry",
        vegan: true,
        description:
          "indisches Currygericht auf Reis mit Tomaten und Kichererbsen",
        price: "9.50",
        variants: [],
      },
      {
        title: "Grünkernfrikadellen",
        vegan: false,
        description: "",
        price: "9.50",
        variants: [
          { variant: "mit Tsatsiki und Brot, mit Salat garniert" },
          {
            variant:
              "mit Tsatsiki und Ofenkartoffeln, mit Salat garniert (+2€)",
          },
        ],
      },
      {
        title: "Vegetarischer Toast",
        vegan: false,
        description: "(Crème fraîche, Tomaten, Gurken, Hirtenkäse und Käse) ",
        price: 5,
        variants: [],
      },
      {
        title: "Gorgonzola-Toast",
        vegan: false,
        description: "(mit Tomaten und Knoblauch)",
        price: 5,
        variants: [],
      },
    ],
  },
  {
    title: "Suppe",
    note: "Zu allen Suppen gibt es Brot. (Weitere Suppen auf der Saisonkarte)",
    products: [
      {
        title: "Afrikanische Erdnuss-Suppe",
        vegan: false,
        description: "",
        price: 4,
        variants: [{ variant: "Groß (+1,50€)" }],
      },
      {
        title: "Möhren-Kartoffel-Suppe",
        vegan: false,
        description: "",
        price: 4,
        variants: [{ variant: "Groß (+1,50€)" }],
      },
    ],
  },
  {
    title: "Toast",
    note: "UnsereToast-Teller werden alle mit einem kleinen Salat garniert.",
    products: [
      {
        title: "Gorgonzola-Toast",
        vegan: false,
        description: "(mit Tomaten und Knoblauch)",
        price: 5,
        variants: [],
      },
      {
        title: "Vegetarischer Toast",
        vegan: false,
        description: "(Crème fraîche, Tomaten, Gurken, Hirtenkäse und Käse)",
        price: 5,
        variants: [],
      },
      {
        title: "Schlemmertoast",
        vegan: false,
        description: "(Schinken, Pilze, Spargel, Eischeiben und Käse)",
        price: 5,
        variants: [],
      },
      {
        title: "Toast Gerakina",
        vegan: false,
        description: "(Schinken, Hirtenkäse, Gurken, Zwiebeln und Käse)",
        price: 5,
        variants: [],
      },
      {
        title: "Toast Hawaii",
        vegan: false,
        description: "(Schinken, Ananas und Käse) ",
        price: 5,
        variants: [],
      },
      {
        title: "Toast Astarix",
        vegan: false,
        description: "(Schinken, Tomaten, Zwiebeln und Käse)",
        price: 5,
        variants: [],
      },
      {
        title: "Gorgonzola-Toast",
        vegan: false,
        description: "(mit Tomaten und Knoblauch)",
        price: 5,
        variants: [],
      },
      {
        title: "Vegetarischer Toast",
        vegan: false,
        description: "(Crème fraîche, Tomaten, Gurken, Hirtenkäse und Käse) ",
        price: 5,
        variants: [],
      },
    ],
  },
  {
    title: "Dessert",
    note: "(weitere Desserts siehe Saisonkarte)",
    products: [
      {
        title: "Hausgemachter veganer Möhrenkuchen",
        vegan: true,
        description: "",
        price: "2.50",
        variants: [],
      },
      {
        title: "Hausgemachter Brownie",
        vegan: false,
        description: "",
        price: "1.90",
        variants: [],
      },
      {
        title: "Hot Brownie",
        vegan: false,
        description: "mit Vanilleeis und Sahne ",
        price: "4.50",
        variants: [],
      },
    ],
  },
  {
    title: "Mineralwasser",
    note: "",
    products: [
      {
        title: "Gerolsteiner Sprudel",
        vegan: true,
        description: "",
        price: "",
        variants: [
          { variant: "0,2l (1,50€)" },
          { variant: "0,4l (2,50€)" },
          { variant: "0,7l (3,50€)" },
        ],
      },
      {
        title: "Gerolsteiner Naturelle",
        vegan: true,
        description: "",
        price: "",
        variants: [
          { variant: "0,2l (1,50€)" },
          { variant: "0,4l (2,50€)" },
          { variant: "1,5l (6,50€)" },
        ],
      },
    ],
  },
  {
    title: "Fruchtiges",
    note: "",
    products: [
      {
        title: "Nabu Apfelsaft",
        vegan: false,
        description: "Naturtrüb aus Streuobstwiesen",
        price: "",
        variants: [{ variant: "0,2l (2,00€)" }, { variant: "0,4l (4,00€)" }],
      },
      {
        title: "Apfelsaft",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "Orangensaft",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "Traubensaft",
        vegan: false,
        description: "rot",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "Kirschnektar",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "Johannisbeernektar",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "Bananennektar",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "Tomatensaft",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "Maracujasaft",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "Mangonektar",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "alle Säfte auch als Schorle",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (3,80€)" }, { variant: "0,2l (1,90€)" }],
      },
    ],
  },
  {
    title: "Limonade",
    note: "",
    products: [
      {
        title: "Club Mate",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,33l (3,50€)" }],
      },
      {
        title: "fritz Apfel-Kirsch-Holunder",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,33l (3,50€)" }],
      },
      {
        title: "fritz Bio Rhabarberschorle",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,33l (3,50€)" }],
      },
      {
        title: "fritz Melonenbrause",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,33l (3,50€)" }],
      },
      {
        title: "fritz Zitronenlimo",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,33l (3,50€)" }],
      },
      {
        title: "fritz-kola Zuckerfrei",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,33l (3,50€)" }],
      },
      {
        title: "fritz-kola",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,33l (3,50€)" }],
      },
      {
        title: "Schweppes Ginger Ale",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "Schweppes Tonic Water",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "Schweppes Bitter Lemon",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (4,00€)" }, { variant: "0,2l (2,00€)" }],
      },
      {
        title: "Zitronenlimonade",
        vegan: false,
        description: "(weiß)",
        price: "",
        variants: [{ variant: "0,4l (3,80€)" }, { variant: "0,2l (1,90€)" }],
      },
      {
        title: "Orangenlimonade",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (3,80€)" }, { variant: "0,2l (1,90€)" }],
      },
      {
        title: "afri Cola light",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (3,80€)" }, { variant: "0,2l (1,90€)" }],
      },
      {
        title: "afri Cola",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,4l (3,80€)" }, { variant: "0,2l (1,90€)" }],
      },
    ],
  },
  {
    title: "Lemonaid+",
    note: "Bio-Limonade aus fairem Handel. Mit frischem Saft, wie hausgemacht.\nDie Zutaten stammen aus ökologischem Anbau und sind Fairtrade-zertifiziert. Jede verkaufte Flasche unterstützt zudem den Lemonaid & ChariTea e.V. und finanziert so soziale Projekte in den Anbauregionen.\nMehr Infos auf www.lemonaid.de",
    products: [
      {
        title: "Lemonaid Maracuja",
        vegan: false,
        description: "Maracujalimonade mit einem Schuss Limette und Mango",
        price: "",
        variants: [{ variant: "0,33l (3,50€)" }],
      },
      {
        title: "Lemonaid Blutorange",
        vegan: false,
        description:
          "Fruchte Blutorangen-Limonade, verfeinert mit Grapefruit, Orange und Zitrone",
        price: "",
        variants: [{ variant: "0,33l (3,50€)" }],
      },
      {
        title: "Lemonaid Limette",
        vegan: false,
        description: "Das Original - mit ganz viel Limettensaft",
        price: "",
        variants: [{ variant: "0,33l (3,50€)" }],
      },
    ],
  },
  {
    title: "Winzerwein aus der Region",
    note: "(Alle Weine enthalten Sulfite)\nWeitere Weinangebote auf der Saisonkarte.",
    products: [
      {
        title: "Riesling",
        vegan: false,
        description:
          "feinherb, aus ökologischem Anbau, Weingut Trossen (Kinheim / Mosel)",
        price: "",
        variants: [
          { variant: "0,1l (2,50€)" },
          { variant: "0,2l (4,50€)" },
          { variant: "1l (17,50€)" },
        ],
      },
      {
        title: "Riesling",
        vegan: false,
        description:
          "trocken, aus ökologischem Anbau, Weingut Trossen (Kinheim / Mosel)",
        price: "",
        variants: [
          { variant: "0,1l (2,50€)" },
          { variant: "0,2l (4,50€)" },
          { variant: "1l (17,50€)" },
        ],
      },
      {
        title: "Elbling",
        vegan: false,
        description:
          "trocken, aus ökologischem Anbau, Weingut Margarethenhof (Tawern / Mosel)",
        price: "",
        variants: [
          { variant: "0,1l (2,50€)" },
          { variant: "0,2l (4,50€)" },
          { variant: "1l (17,50€)" },
        ],
      },
      {
        title: "Grauburgunder",
        vegan: false,
        description: "trocken, Weingut Reuter (Konz)",
        price: "",
        variants: [{ variant: "0,1l (2,50€)" }, { variant: "0,2l (4,50€)" }],
      },
      {
        title: "Blanc de Noir",
        vegan: false,
        description: "feinherb, Weingut Reuter (Konz)",
        price: "",
        variants: [{ variant: "0,1l (2,50€)" }, { variant: "0,2l (4,50€)" }],
      },
      {
        title: "Landwein rot",
        vegan: false,
        description: "trocken, aus ökologischem Anbau, Weingut Reuter (Konz)",
        price: "",
        variants: [{ variant: "0,1l (2,50€)" }, { variant: "0,2l (4,50€)" }],
      },
      {
        title: "Lambrusco",
        vegan: false,
        description: "Weingut Reuter (Konz)",
        price: "",
        variants: [{ variant: "0,1l (2,50€)" }, { variant: "0,2l (4,50€)" }],
      },
      {
        title: "Landwein rosé",
        vegan: false,
        description: "trocken, Weingut Reuter (Konz)",
        price: "",
        variants: [{ variant: "0,1l (2,50€)" }, { variant: "0,2l (4,50€)" }],
      },
      {
        title: "Weinschorle",
        vegan: false,
        description: "Weingut Reuter (Konz), 0,4l",
        price: "3.50",
        variants: [],
      },
    ],
  },
  {
    title: "Viez",
    note: "",
    products: [
      {
        title: "Trierer Viez",
        vegan: false,
        description: "(J. Lorscheider / Wasserliesch)",
        price: "",
        variants: [{ variant: "0,2l (1,30€)" }, { variant: "0,4l (2,30€)" }],
      },
      {
        title: "Trierer Viez",
        vegan: false,
        description: "(E. Weyand / Biewer)",
        price: "",
        variants: [{ variant: "0,2l (1,30€)" }, { variant: "0,4l (2,30€)" }],
      },
      {
        title: "Viez-Pass",
        vegan: false,
        description: "(Stempelkarte für 10 Viez, à 0,4 L)",
        price: 21,
        variants: [],
      },
    ],
  },
  {
    title: "Flaschenbier",
    note: "",
    products: [
      {
        title: "Bitburger",
        vegan: false,
        description: "0,0%, 0,33l",
        price: "2.60",
        variants: [{ variant: "Grapefruit" }, { variant: "Pils" }],
      },
      {
        title: "Kandi Malzbier",
        vegan: false,
        description: "Kandi Malz, 0,33l",
        price: "2.60",
        variants: [],
      },
      {
        title: "Köstritzer Schwarzbier",
        vegan: false,
        description: "nur im Miss Marples, 0,33l",
        price: "2.60",
        variants: [],
      },
      {
        title: "Köstritzer Schwarzbier",
        vegan: false,
        description: "nur im Miss Marples, 0,5l",
        price: "3.90",
        variants: [],
      },
      {
        title: "Benediktiner Weissbier",
        vegan: false,
        description: "0,5l",
        price: "",
        variants: [
          { variant: "Naturtrüb (3,90€)" },
          { variant: "Dunkel (3,90€)" },
          { variant: "Alkoholfrei (3,90€)" },
        ],
      },
    ],
  },
  {
    title: "Bier vom Fass",
    note: "",
    products: [
      {
        title: "Bitburger Premium Pils",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,3l (2,60€)" }, { variant: "0,4l (3,40€)" }],
      },
      {
        title: "Köstritzer Schwarzbier",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,3l (2,60€)" }, { variant: "0,4l (3,40€)" }],
      },
      {
        title: "Köstritzer Kellerbier",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,3l (2,60€)" }, { variant: "0,4l (3,40€)" }],
      },
      {
        title: "Bier-Pass",
        vegan: false,
        description: "(Stempelkarte für 10 Bier, à 0,4l)",
        price: 32,
        variants: [],
      },
    ],
  },
  {
    title: "Sekt",
    note: "",
    products: [
      {
        title: "Hausmarke",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "0,1l (3€)" }, { variant: "0,75l (16,50€)" }],
      },
      {
        title: "Prosseco",
        vegan: false,
        description: "0,1l",
        price: "2.50",
        variants: [],
      },
      {
        title: "Aperol Spritz ",
        vegan: false,
        description: "",
        price: "5.50",
        variants: [],
      },
    ],
  },
  {
    title: "Aperetif",
    note: "",
    products: [
      {
        title: "Ricard",
        vegan: false,
        description: "",
        price: 2,
        variants: [],
      },
      {
        title: "Martini Bianco",
        vegan: false,
        description: "",
        price: 3,
        variants: [],
      },
      {
        title: "Martini Rosso",
        vegan: false,
        description: "",
        price: 3,
        variants: [],
      },
      {
        title: "Longdrinks",
        vegan: false,
        description: "mit 4cl",
        price: 6,
        variants: [],
      },
      {
        title: "Tequila Sunrise",
        vegan: false,
        description: "",
        price: 6,
        variants: [],
      },
      {
        title: "Campari Orange",
        vegan: false,
        description: "",
        price: 6,
        variants: [],
      },
    ],
  },
  {
    title: "Likör",
    note: "",
    products: [
      {
        title: "Batida de Coco",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Baileys",
        vegan: false,
        description: "enthält Milch, 2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Pfefferminz",
        vegan: false,
        description: "2cl",
        price: "1.50",
        variants: [],
      },
    ],
  },
  {
    title: "Cocktail",
    note: "",
    products: [
      {
        title: "Caipirinha",
        vegan: false,
        description: "",
        price: 6,
        variants: [],
      },
      {
        title: "Cuba Libre",
        vegan: false,
        description: "",
        price: 6,
        variants: [],
      },
    ],
  },
  {
    title: "Spirituosen",
    note: "",
    products: [
      {
        title: "Ouzo",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Gordon‘s Gin",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Jose CuervoTequila Silber",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Jose CuervoTequila Gold",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Moskovskaya Vodka",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Pâpidoux Calvados",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Molinari Sambuca",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
    ],
  },
  {
    title: "Whisky",
    note: "mit Cola (+1€)",
    products: [
      {
        title: "Johnny Walker Red Label",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "2cl (2,80€)" }, { variant: "4cl (5€)" }],
      },
      {
        title: "Tullamore Dew",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "2cl (2,80€)" }, { variant: "4cl (5€)" }],
      },
      {
        title: "Jack Daniels",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "2cl (2,80€)" }, { variant: "4cl (5€)" }],
      },
      {
        title: "Glenfiddich Single Malt",
        vegan: false,
        description: "",
        price: "",
        variants: [{ variant: "2cl (3,20€)" }, { variant: "4cl (6€)" }],
      },
    ],
  },
  {
    title: "Digestif",
    note: "",
    products: [
      {
        title: "Ramazzotti",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Averna",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Fernet Branca",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Jägermeister",
        vegan: false,
        description: "2cl",
        price: 2,
        variants: [],
      },
      {
        title: "Remy Martin",
        vegan: false,
        description: "2cl",
        price: "3.50",
        variants: [],
      },
      {
        title: "Grappa di Barolo",
        vegan: false,
        description: "2cl",
        price: "3.50",
        variants: [],
      },
    ],
  },
  {
    title: "Obstbrände aus der Region",
    note: "Hubertus Brennerei, Wintersdorf",
    products: [
      {
        title: "Nelsches-Birne Edelbrand",
        vegan: false,
        description: "2cl",
        price: "2.50",
        variants: [],
      },
      {
        title: "Mirabelle Edelbrand",
        vegan: false,
        description: "2cl",
        price: "2.50",
        variants: [],
      },
      {
        title: "Zwetschgen Edelbrand",
        vegan: false,
        description: "2cl",
        price: "2.50",
        variants: [],
      },
      {
        title: "Viez-Likör",
        vegan: false,
        description: "2cl",
        price: "2.50",
        variants: [],
      },
      {
        title: "Pfirsich-Likör",
        vegan: false,
        description: "2cl",
        price: "2.50",
        variants: [],
      },
      {
        title: "Brombeer-Likör",
        vegan: false,
        description: "2cl",
        price: "2.50",
        variants: [],
      },
    ],
  },
  {
    title: "Kaffee",
    note: "Alle Kaffeesorten gibt‘s bei uns auch koffeinfrei und auf Wunsch mit Sojamilch!",
    products: [
      {
        title: "Kaffee",
        vegan: false,
        description: "",
        price: "2.20",
        variants: [{ variant: "Groß (+1,30€)" }],
      },
      {
        title: "Milchkaffe",
        vegan: false,
        description: "",
        price: "3.50",
        variants: [],
      },
      {
        title: "Latte Macchiatio",
        vegan: false,
        description: "",
        price: "3.50",
        variants: [],
      },
      {
        title: "Caro Kaffee",
        vegan: false,
        description: "",
        price: "2.20",
        variants: [],
      },
      {
        title: "Caro Latte",
        vegan: false,
        description: "",
        price: "3.50",
        variants: [],
      },
      {
        title: "Espresso",
        vegan: false,
        description: "",
        price: "2.20",
        variants: [{ variant: "doppelt (3,50€)" }],
      },
      {
        title: "Espresso Macchiatio",
        vegan: false,
        description: "",
        price: "2.20",
        variants: [],
      },
      {
        title: "Cappuccino",
        vegan: false,
        description: "",
        price: "2.80",
        variants: [{ variant: "doppelt (4,50€)" }],
      },
    ],
  },
  {
    title: "ChariTea",
    note: " ChariTea - eine Kollektion ausgewählter Bio-Tees.\nBeste Zutaten aus biologischem Anbau und Fairem Handel . Ohne künstliche Aromen, Farbstoffe und andere Zusätze.",
    products: [
      {
        title: "ChariTea african summer",
        vegan: false,
        description:
          "Rooibos-Tee aus Südafrika, verfeinert mit Orange und Vanille, aus biologischem Anbau und Zutaten aus fairem Handel.",
        price: "2.50",
        variants: [],
      },
      {
        title: "ChariTea arabian mint",
        vegan: false,
        description:
          "Kräutertee-Mischung mit Pfefferminze und Kraueminze aus Ägypten, aus biologischem Anbau und Zutaten aus fairem Handel.",
        price: "2.50",
        variants: [],
      },
      {
        title: "ChariTea oriental nights",
        vegan: false,
        description:
          "Gewürztee mit fruchtigem Apfel, schwarf-würzigem Ingwer, Zimt und Sternanis.Verfeindert mit süßen Feigen und Granatapfelkernen.",
        price: "2.50",
        variants: [],
      },
      {
        title: "ChariTea masala chai",
        vegan: false,
        description:
          "Traditionelle Chai-Tee Mischung, aus biologischem Anbau und Zutaten aus fairem Handel.",
        price: "2.50",
        variants: [{ variant: "auch als Chai Latte erhältlich (3,50€)" }],
      },
    ],
  },
  {
    title: "Tee",
    note: "",
    products: [
      {
        title: "Schwarzer Tee",
        vegan: false,
        description: "",
        price: "2.50",
        variants: [{ variant: "Darjeeling" }, { variant: "Earl Grey" }],
      },
      {
        title: "Grüner Tee",
        vegan: false,
        description: "",
        price: "2.50",
        variants: [
          { variant: "grüner Tee Jasmin (Alnatura)" },
          { variant: "weißer Tee Kirschblüte" },
        ],
      },
      {
        title: "Früchtetee",
        vegan: false,
        description: "",
        price: "2.50",
        variants: [
          { variant: "italienische Limone" },
          { variant: "mediterraner Pfirsisch" },
        ],
      },
      {
        title: "Kräutertee",
        vegan: false,
        description: "",
        price: "2.50",
        variants: [
          { variant: "Kamille" },
          { variant: "Minze" },
          { variant: "Kräuter" },
          { variant: "orientalischer Gewürztee" },
          { variant: "Salbei-Honig-Vanille" },
          { variant: "Moringa-Matte-Ingwer" },
          { variant: "Ingwer 100%" },
          { variant: "Masir" },
          { variant: "Fenchel" },
        ],
      },
      {
        title: "Heiße Zitrone",
        vegan: false,
        description: "",
        price: "2.50",
        variants: [],
      },
      {
        title: "Grog",
        vegan: false,
        description: "(mit 4 cl Rum)",
        price: "3.80",
        variants: [],
      },
    ],
  },
];
